### ISSUE TITLE
SeekFromCurrent and SeekFromEnd are not tested

### ISSUE THREAD

**Issue by briandfoy** [perl6/roast#219]
They are documented and they seem to work, but there are no tests for them.

**Comment by zoffixznet** [comment]
Fixed. Thanks.

I left failure modes untested for now. They look inconsistent and we might want to `fail` instead of `throwing`. Will figure out as part of IO improvement. I hope parts that can be merged into 6.c language to be done and merged by end of February. So you'll know those details early enough to be accurate in the book.
