### ISSUE TITLE
need test for $*INITTIME

### ISSUE THREAD

**Issue by gfldex** [perl6/roast#296]

**Comment by zoffixznet** [comment]
Would be nice if it were renamed to `$*INIT-TIME` to follow the kebob-case of all our other multi-word dynvars and methods

**Comment by AlexDaniel** [comment]
Also maybe $*INIT-INSTANT so that it does not look like ``INIT time``. :/

**Comment by mryan** [comment]
Wasn't sure if the intent with this was to leave it alone until the rename or not.  In the end I thought it may be better to have the tests sorted and leave the rename to be exclusively that - just a rename.
See my PR - I'm uncertain
  - as to whether to use a seperate file or merge with (which?) existing?
  - the near-arbitrary selection of a 1-second tolerance b/w $*INITTIME and "my $var = INIT now;"
    On the old imac I'm on here, there was around 100-200mS difference between the two.
Thoughts and/or advice?

**Comment by zoffixznet** [comment]
Rename carried out in https://github.com/rakudo/rakudo/commit/6bdb2dd368 and specced in https://github.com/perl6/roast/commit/84b48ec92b

@mryan a tip for the future: when you add new test files to roast they also need to be added to Rakudo's [t/spectest.data file](https://github.com/rakudo/rakudo/blob/nom/t/spectest.data). Otherwise they'll never get run. (I already added the file your PR added)

**Comment by mryan** [comment]
@zoffix - Thanks.  I read about the need to update spectest.data in CONTRIBUTING.  I didn't do so because of the uncertainties I listed above.  Cheers.
